import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { X, Code, ChevronDown, ChevronUp, FileText } from "lucide-react";
export default function ComposerPreview({ uploadedImages, onRemoveImage, codeCards, collapsedMap, onToggleCodeCard, textAttachments = [], onRemoveTextAttachment, }) {
    return (_jsxs(_Fragment, { children: [textAttachments.length > 0 && (_jsx("div", { className: "mb-3 flex flex-wrap gap-2", children: textAttachments.map((attachment) => {
                    // 截取前几行预览
                    const previewLines = attachment.content.split(/\r?\n/).slice(0, 4);
                    const preview = previewLines.join('\n');
                    const hasMore = attachment.lineCount > 4;
                    return (_jsxs("div", { className: "group relative w-[125px] rounded-lg border border-slate-600/60 bg-slate-800/60 hover:bg-slate-700/60 transition-colors overflow-hidden", children: [_jsxs("div", { className: "flex items-center justify-between px-2 py-1.5 bg-slate-700/30", children: [_jsxs("div", { className: "flex items-center gap-1.5 min-w-0", children: [_jsx(FileText, { size: 12, className: "text-blue-400 shrink-0" }), _jsx("span", { className: "text-slate-200 text-xs font-medium truncate", children: attachment.fileName }), _jsxs("span", { className: "text-slate-500 text-[10px] shrink-0", children: [attachment.lineCount, "\u884C"] })] }), onRemoveTextAttachment && (_jsx("button", { type: "button", onClick: () => onRemoveTextAttachment(attachment.id), className: "p-0.5 rounded hover:bg-slate-500/50 text-slate-400 hover:text-red-400 transition shrink-0", title: "\u5220\u9664\u9644\u4EF6", "aria-label": "\u5220\u9664\u9644\u4EF6", children: _jsx(X, { size: 12 }) }))] }), _jsxs("div", { className: "px-2 py-1.5 text-[10px] text-slate-400 font-mono whitespace-pre-wrap break-all max-h-20 overflow-hidden leading-tight", children: [preview, hasMore && (_jsx("span", { className: "text-slate-500 italic", children: "..." }))] })] }, attachment.id));
                }) })), codeCards.length > 0 && (_jsx("div", { className: "mb-3 space-y-2", children: codeCards.map((card) => {
                    const collapsed = collapsedMap[card.id] ?? true;
                    const lines = card.code ? card.code.split("\n").length : 0;
                    return (_jsxs("div", { className: "rounded-lg border border-slate-700/50 bg-slate-800/50 overflow-hidden", children: [_jsxs("div", { className: "flex items-center justify-between px-3 py-2 bg-slate-700/30 cursor-pointer hover:bg-slate-700/50 transition", onClick: () => onToggleCodeCard(card.id), role: "button", tabIndex: 0, onKeyDown: (e) => {
                                    if (e.key === "Enter" || e.key === " ")
                                        onToggleCodeCard(card.id);
                                }, "aria-label": `切换代码块 ${card.language || "code"} 展开/折叠`, children: [_jsxs("div", { className: "flex items-center gap-2 text-sm text-slate-300", children: [_jsx(Code, { size: 14 }), _jsx("span", { children: card.language || "code" }), _jsxs("span", { className: "text-xs text-slate-500", children: ["(", lines, " \u884C)"] })] }), collapsed ? (_jsx(ChevronDown, { size: 16, className: "text-slate-400" })) : (_jsx(ChevronUp, { size: 16, className: "text-slate-400" }))] }), !collapsed && (_jsx("pre", { className: "p-3 text-xs text-slate-200 overflow-x-auto max-h-48 overflow-y-auto", children: _jsx("code", { children: card.code }) }))] }, card.id));
                }) })), uploadedImages.length > 0 && (_jsx("div", { className: "mb-3 flex flex-wrap gap-2", children: uploadedImages.map((img) => (_jsxs("div", { className: "relative group rounded-lg overflow-hidden border border-slate-700/50", children: [_jsx("img", { src: img.preview, alt: "Upload preview", className: "h-20 w-20 object-cover" }), _jsx("button", { type: "button", onClick: () => onRemoveImage(img.id), className: "absolute top-1 right-1 p-1 rounded-full bg-slate-900/80 text-slate-100 opacity-0 group-hover:opacity-100 transition-opacity hover:bg-red-600", title: "\u5220\u9664\u56FE\u7247", "aria-label": "\u5220\u9664\u56FE\u7247", children: _jsx(X, { size: 14 }) })] }, img.id))) }))] }));
}
