import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { UserCircle, Plus, Loader2, ChevronDown, ChevronRight, Users } from 'lucide-react';
import { useBackgroundLoading } from '../hooks/useBackgroundLoading';
export const RoleList = ({ roles, selectedRoleId, onSelectRole, onCreateClick, onEditRole, isCollapsed = false, }) => {
    const [failedAvatars, setFailedAvatars] = useState({});
    const [isExpanded, setIsExpanded] = useState(true);
    // ✅ 获取所有正在 loading 的 agent，用于在列表中显示思考指示器
    const { allLoadingAgentIds } = useBackgroundLoading(selectedRoleId);
    const loadingSet = new Set(allLoadingAgentIds);
    return (_jsxs("div", { className: "flex flex-col bg-slate-50 text-slate-900 dark:bg-slate-900/40 dark:text-slate-100", children: [_jsx("div", { className: `p-2 border-b border-slate-200 bg-white/70 backdrop-blur dark:border-slate-800 dark:bg-slate-900/70 ${isCollapsed ? 'flex justify-center' : 'flex items-center justify-between'}`, children: isCollapsed ? (_jsx("button", { onClick: () => setIsExpanded(!isExpanded), className: "p-2 rounded-lg transition-colors hover:bg-slate-100 dark:hover:bg-slate-800", title: isExpanded ? "折叠 Agents" : "展开 Agents", children: _jsx(Users, { size: 20, className: "text-slate-600 dark:text-slate-400" }) })) : (_jsxs(_Fragment, { children: [_jsxs("button", { onClick: () => setIsExpanded(!isExpanded), className: "flex items-center gap-2 flex-1 hover:bg-slate-100 dark:hover:bg-slate-800/50 rounded-md px-2 py-1 transition-colors", children: [isExpanded ? _jsx(ChevronDown, { size: 16 }) : _jsx(ChevronRight, { size: 16 }), _jsx("h2", { className: "font-semibold text-slate-700 dark:text-slate-200", children: "Agents" }), roles.length > 0 && (_jsx("span", { className: "text-xs text-slate-500 bg-slate-200 dark:bg-slate-800 px-1.5 py-0.5 rounded", children: roles.length }))] }), _jsx("button", { onClick: onCreateClick, className: "p-2 rounded-full transition-colors\n                         hover:bg-slate-100 active:scale-[0.98]\n                         dark:hover:bg-slate-800", title: "\u521B\u5EFA Agent", children: _jsx(Plus, { size: 18, className: "text-blue-600 dark:text-blue-400" }) })] })) }), isExpanded && (_jsxs("div", { className: "py-2 overflow-y-auto max-h-[50vh]", children: [roles.map((role) => {
                        const active = selectedRoleId === role.id;
                        const isThinking = loadingSet.has(role.id);
                        return (_jsxs("div", { className: "group w-full flex items-center justify-between", children: [_jsxs("button", { onClick: () => onSelectRole(role), className: [
                                        isCollapsed ? 'w-full py-2 flex justify-center' : 'w-full text-left px-4 py-3 flex items-center gap-3',
                                        'transition-colors rounded-xl mx-2',
                                        'hover:bg-slate-100 dark:hover:bg-slate-800/60',
                                        active && 'bg-slate-200 dark:bg-slate-800',
                                    ].join(' '), title: isCollapsed ? role.name : undefined, children: [_jsxs("div", { className: "shrink-0 relative", children: [role.avatar && !failedAvatars[role.id] ? (_jsx("img", { src: role.avatar, alt: role.name, className: "h-8 w-8 rounded-full object-cover", onError: () => setFailedAvatars((s) => ({ ...s, [role.id]: true })) })) : (_jsx(UserCircle, { size: 34, className: ['text-slate-400'].join(' ') })), isThinking && (_jsx("div", { className: "absolute -bottom-0.5 -right-0.5 w-4 h-4 bg-blue-500 rounded-full flex items-center justify-center ring-2 ring-white dark:ring-slate-900", children: _jsx(Loader2, { size: 10, className: "animate-spin text-white" }) }))] }), !isCollapsed && (_jsx("div", { className: "flex-1 min-w-0", children: _jsxs("p", { className: [
                                                    'font-medium truncate',
                                                ].join(' '), children: [role.name, isThinking && (_jsx("span", { className: "ml-2 text-xs font-normal text-blue-500 dark:text-blue-400", children: "\u601D\u8003\u4E2D..." }))] }) }))] }), !isCollapsed && (_jsx("div", { className: "pr-2 opacity-0 group-hover:opacity-100 transition-opacity", children: _jsx("button", { onClick: () => onEditRole?.(role), className: "p-1 rounded-md hover:bg-slate-100 dark:hover:bg-slate-800/60", title: "Edit", children: _jsxs("svg", { width: "14", height: "14", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: "2", strokeLinecap: "round", strokeLinejoin: "round", className: "text-slate-500", children: [_jsx("path", { d: "M12 20h9" }), _jsx("path", { d: "M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4 12.5-12.5z" })] }) }) }))] }, role.id));
                    }), roles.length === 0 && !isCollapsed && (_jsxs("div", { className: "px-4 py-10 text-center text-sm text-slate-500 dark:text-slate-400", children: ["\u6682\u65E0 Agents\uFF0C\u70B9\u51FB\u53F3\u4E0A\u89D2 ", _jsx("span", { className: "font-semibold", children: "+" }), " \u521B\u5EFA\u4E00\u4E2A\u5427"] }))] }))] }));
};
